apiVersion: tekton.dev/v1
kind: Task
metadata: 
  name: welcome-user-task
spec:
  params:
  - name: username
    type: string
    default: "user"
  steps:
    - name: welcome-user
      image: alpine
      script: |
        #1/bin/sh
        echo "Welcome $(params.username)"